Repository microsoft/MixedReality-SpectatorView, pull requests merged in 2019-10, with the labels that each got.

#213 Add tests for video camera video recording and fix subsequent recording
  samples/SpectatorView.Example.Unity/ProjectSettings/EditorBuildSettings.asset
  src/SpectatorView.Native/SpectatorView.Compositor/Compositor/CompositorInterface.cpp
  src/SpectatorView.Native/SpectatorView.Compositor/Compositor/CompositorInterface.h
  src/SpectatorView.Native/SpectatorView.Compositor/Compositor/DirectoryHelper.cpp
  src/SpectatorView.Native/SpectatorView.Compositor/Compositor/DirectoryHelper.h
  src/SpectatorView.Native/SpectatorView.Compositor/Compositor/VideoEncoder.cpp
  src/SpectatorView.Native/SpectatorView.Compositor/Compositor/VideoEncoder.h
  src/SpectatorView.Native/SpectatorView.Compositor/UnityPlugin/UnityCompositorInterface.cpp
  src/SpectatorView.Unity/Assets/SpectatorView.Editor/Scenes/SpectatorViewCompositor.unity
  src/SpectatorView.Unity/Assets/SpectatorView.Editor/Scripts/CompositorWindow.cs
  src/SpectatorView.Unity/Assets/SpectatorView.Tests.meta
  src/SpectatorView.Unity/Assets/SpectatorView.Tests/CompositionManagerTests.cs
  src/SpectatorView.Unity/Assets/SpectatorView.Tests/CompositionManagerTests.cs.meta
  src/SpectatorView.Unity/Assets/SpectatorView.Tests/CompositorTestsBase.cs
  src/SpectatorView.Unity/Assets/SpectatorView.Tests/CompositorTestsBase.cs.meta
  src/SpectatorView.Unity/Assets/SpectatorView.Tests/Microsoft.MixedReality.SpectatorView.Tests.asmdef
  src/SpectatorView.Unity/Assets/SpectatorView.Tests/Microsoft.MixedReality.SpectatorView.Tests.asmdef.meta
  src/SpectatorView.Unity/Assets/SpectatorView.Tests/TextureManagerTests.cs
  src/SpectatorView.Unity/Assets/SpectatorView.Tests/TextureManagerTests.cs.meta
  src/SpectatorView.Unity/Assets/SpectatorView/Audio.meta
  src/SpectatorView.Unity/Assets/SpectatorView/Audio/C.wav
  src/SpectatorView.Unity/Assets/SpectatorView/Audio/C.wav.meta
  src/SpectatorView.Unity/Assets/SpectatorView/Materials/RecordingTestCubeMaterial.mat
  src/SpectatorView.Unity/Assets/SpectatorView/Materials/RecordingTestCubeMaterial.mat.meta
  src/SpectatorView.Unity/Assets/SpectatorView/Prefabs/Recording Test Objects.prefab
  src/SpectatorView.Unity/Assets/SpectatorView/Prefabs/Recording Test Objects.prefab.meta
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Compositor/CompositionManager.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Compositor/UnityCompositorInterface.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Test.meta
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Test/RecordingTestCube.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Test/RecordingTestCube.cs.meta
  tools/Scripts/CopyPluginsToUnity.ps1
Labels: breaking change

#232 Add gradle issues to azure spatial anchor troubleshooting
  doc/SpectatorView.Setup.md
Labels: documentation

#233 Add additional information around marker visual detection
  src/SpectatorView.Unity/Assets/SpatialAlignment/README.md
Labels: documentation

#234 Enable resetting spatial alignment.
  src/SpectatorView.Unity/Assets/SpatialAlignment.ASA/Scripts/SpectatorView/SpatialAnchorsCoordinateLocalizationInitializer.cs
  src/SpectatorView.Unity/Assets/SpatialAlignment.ASA/Scripts/SpectatorView/SpatialAnchorsLocalizer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Prefabs/Default Mobile UI.prefab
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/ScreenRecording/AndroidRecordingService.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/ISpatialLocalizationSession.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/MarkerVisual/MarkerVisualCoordinateService.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/MarkerVisual/MarkerVisualDetectorSpatialLocalizer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/MarkerVisual/MarkerVisualLocalizationInitializer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/MarkerVisual/MarkerVisualSpatialLocalizer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/PhysicalMarker/MarkerDetectorSpatialLocalizer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/SpatialCoordinateSystemManager.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/SpatialLocalizationInitializer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/WorldAnchor/WorldAnchorSpatialLocalizer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpectatorView.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/UI/SpatialAlignmentVisual.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/UI/SpatialAlignmentVisual.cs.meta
Labels: breaking change

#247 Enable cancelling localization sessions
  src/SpectatorView.Unity/Assets/SpatialAlignment.ASA/Scripts/SpatialAlignment/SpatialAnchorsAndroidCoordinateService.cs
  src/SpectatorView.Unity/Assets/SpatialAlignment.ASA/Scripts/SpectatorView/SpatialAnchorsLocalizer.cs
  src/SpectatorView.Unity/Assets/SpatialAlignment/Scripts/Utilities/Extensions.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Prefabs/Default Mobile UI.prefab
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Socketer/TCPConnectionManager.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/ISpatialLocalizationSession.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/MarkerVisual/MarkerVisualDetectorSpatialLocalizer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/MarkerVisual/MarkerVisualSpatialLocalizer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/PhysicalMarker/MarkerDetectorSpatialLocalizer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/SpatialCoordinateSystemManager.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/SpatialCoordinateTransformer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/SpatialLocalizationSession.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/SpatialLocalizationSession.cs.meta
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpatialAlignment/WorldAnchor/WorldAnchorSpatialLocalizer.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/SpectatorView.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/UI/SpatialAlignmentVisual.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Utilities/Dispatcher.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Utilities/Dispatcher.cs.meta
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Utilities/DispatcherUnity.cs
  src/SpectatorView.Unity/Assets/SpectatorView/Scripts/Utilities/DispatcherUnity.cs.meta
Labels: breaking change

#255 Fix the powershell to get all symbolic links and restore them
  tools/Scripts/SymbolicLinkHelpers.psm1
Labels: bug
